import { Contacto } from "./contacto";
import { Direccion } from "./direccion";

export interface Cliente {
    codigoCliente: string;
    nombre: string;
    ruc: string;
    direccion: string;
    codListaPrecio: string;
    codVendedor: string;
    codCondPago: string;
    lineaCredito: Number;
    saldoDisponible: Number;
    nombreComercial: string;
    tpoPersona: string;
    tpoDocumento: string;
    primerNombre: string;
    segundoNombre: string;
    apellidoPaterno: string;
    apellidoMaterno: string;    
    telefonoCliente: string;
    celularCliente: string;
    correoCliente: string;
    grupoCliente: string;
    agenteRetencion: boolean;
    buenContribuyente: boolean;
    flag: boolean;
    u_EK_NMCONDPG: string;
    u_EXK_SOLCRED: string;
    u_EXK_IMPCRED: string;
    u_EXK_MNDCRED: string;
    u_EXK_NOTCRED: string;
    u_EXK_AUTCRED: string;
    u_EXK_SOLSOB: string;
    u_EXK_PORSOB: string;
    u_EXK_NCRESOB: string;
    u_EXK_AUTSOB: string;
    u_EXK_SCCONPAG: string;
    u_EXK_CONDPAGO: string;
    u_EXK_NCCONDPAG: string;
    u_EXK_CDPAGAUT: string;
    currency: string;
    industryC: Number;
    codDireccion: string;
    zona: string;
    shipType: string;
    listaDireccion: Direccion[];
    listaContacto: Contacto[];
}